### ISSUE TITLE
Palazzetti BIANCA LUX 9 - Ducted FAN issue

### ISSUE THREAD

**Issue by JiMSigneLesArbres** [marcopal74/home-assistant-palazzetti#5] opened 2022-02-25 12:09 UTC
Thanks a lot for your great job on this integration.
I have an issue when I want to control the second FAN :-/
![2022-02-25 13_07_11-](https://user-images.githubusercontent.com/76914711/155712752-1ba94374-be63-4a92-a626-72e9b3227291.png)

The BIANCA LUX have 2 controlable FANs.
The second FAN is detected, but FAN vakue is in fan_third ... so it doesn't work :

"_flag_has_fan_main: true
_flag_has_fan_second: true
_flag_has_fan_third: false"
[...]
"_value_power: 2
_value_fan_main: 7
_value_fan_second: 0
_value_fan_third: 2
_value_fan_limits:
  - 0
  - 5
  - 0
  - 5
  - 0
  - 5
_value_door_status: null"

**Comment by JiMSigneLesArbres** [comment] 2022-02-25 18:12
May I do something from my side to make it work ?

**Comment by marcopal74** [comment] 2022-02-25 18:36
Thank you for your feedback!
To debug the issue could you please send me also the **Attributes** of the entity "Product"? Thank you

<img width="387" alt="Schermata 2022-02-25 alle 19 32 43" src="https://user-images.githubusercontent.com/28279074/155769203-544afa78-391b-4c18-96ce-62335d0a590a.png">

**Comment by JiMSigneLesArbres** [comment] 2022-02-25 20:00
product attibutes :

PSENSLTSH
0
HWTYPE
7
NOMINALPWR
9
AUTONOMYTYPE
1
STOVETYPE
1
CHRONOTYPE
5
SPLMIN
6
DSPFWVER
32
MOD
1 205
FAN2MODE
3
FAN2TYPE
3
SPLMAX
51
FLUID
0
PELLETTYPE
3
PSENSLMIN
0
SNCHK
1
PSENSLMAX
0
PSENSTYPE
0
CONFIG
1
BLEMBMODE
13
UICONFIG
1
BLEDSPMODE
1
MAINTPROBE
4
FWDATE
31 octobre 2019
VER
4
MBTYPE
0
CORE
30
SN
LT202007380580457225995
T2
40,7
F2LF
2
PQT
2 871
PWR
4
CHRSTATUS
0
FANLMINMAX
1, 5, 0, 5, 0, 5
FDR
0
F2V
130
DPT
0
APLWDAY
5
SETP
19
STATUS
11
T3
307
T1
0
PUMP
0
T5
20,5
F1RPM
2 222
OUT
22
F1V
2 222
EFLAGS
0
LSTATUS
11
T4
0
F3L
0
F2L
7
F4L
2
IN
11
DP
0
IGNERRORS
2
POWERTIME
10752:46
SERVICETIME
1250:14
OVERTMPERRORS
0
HEATTIME
3171:59
ONTIME
206:16
IGN
1 076
STATE
CLEANFIRE

**Comment by JiMSigneLesArbres** [comment] 2022-02-25 20:06
Thank you for you quick answer.

![2022-02-25 21_03_23-](https://user-images.githubusercontent.com/76914711/155788912-d29a42ee-b742-4fdd-99fb-e4083f446fa5.png)
Yes, sliders works, except "Fan L". : if I try to change it, all is grey and 'set value error' occur.

**Comment by JiMSigneLesArbres** [comment] 2022-02-25 22:03
On iOS Palazzetti app, the FAN is not considered as Left Fan, but Right Fan. If it can help. 
![image](https://user-images.githubusercontent.com/76914711/155809229-ae5a602d-d891-418c-9429-e4e4a68000a3.jpeg)

**Comment by marcopal74** [comment] 2022-02-25 22:55
From the attributes you have sent I was aspecting F3L=2 and F4L=0. Let me check more in deep if it's an error of the asset_parser library issued by the Company or a wrong interpretation of the palazzetti_sdk_local_api.
This integration sends the command SET F3L instead of SET F4L and this is the cause of the error.
I cannot simulate the error but you could make this change to the file `Input_number.py` located in `custom_components/palazzetti` folder in your `config` path:
```
...

# slider impostazione secondo ventilatore
    if _config["_flag_has_fan_second"]:
        fan = 3
        data4 = {
            "id": f"{config_entry.unique_id}_fan2",
            "initial": _config["_value_fan_third"],
            "max": _config["_value_fan_limits"][(((fan - 1) * 2) + 1)],
            "min": _config["_value_fan_limits"][((fan - 1) * 2)],
            "mode": "slider",
            "name": "Fan R",
            "step": 1.0,
            "icon": "mdi:fan-speed-2",
        }
        slider_fan2 = MyNumber(hass, data4, product, "fan3", config_entry.unique_id)
        entity_list.append(slider_fan2)

...
```
I attach also a picture to understand the correction:
![image](https://user-images.githubusercontent.com/28279074/155813698-ef0b20e5-6b36-44e1-8d33-91315bd722e8.jpeg)

I cannot test it but basically we are setting the second fan as it were the third.
Remember to restart Home Assistant after having edited the file.

Hope it works 🤞🏻

**Comment by marcopal74** [comment] 2022-02-25 23:19
Issue found: merged a PR to solve the issue. Update the integration with the new one and the problem should be solved.

THANK YOU very much for the informations, this is what makes free code better!!

**Closed** 2022-02-25 23:20 UTC
Labels: question

**Comment by JiMSigneLesArbres** [comment] 2022-02-26 00:39
Thank you a lot 👍🏻
Problem solved for FAN R !
Great job, and very quick 💪🏻 thank you 😊

**Comment by JiMSigneLesArbres** [comment] 2022-02-26 00:45
Thank you again. 
I’ve just seen another problem. I don’t know if I have to create another issue or not :

Main Fan slider is set with max value to 5, but 7 ( means auto ) is a correct value. 
When I set auto on the IOS app, the slider change to 7. But how to set it to 7 with the slider ?
